import { CONFIG } from './config.js'; import { buildGrid, nearbyFromGrid, angleDifference } from './geo.js'; import { readDataset, downloadDataset, refreshDataset } from './storage.js'; import { OrientationController } from './orientation.js'; import { getDepartures } from '../api/departures.js';
import { datasetReadyMessage } from './dataset-status.js';
const $ = id => document.getElementById(id), debug = new URLSearchParams(location.search).get('debug') === '1';
const state = { dataset:null, grid:null, position:null, heading:0, nearby:[], selected:null, aimed:null, dwellAt:0, lockedUntil:0, stream:null, watch:null, poll:null, realtime:'idle', installPrompt:null };
function isMobile() { const ua = navigator.userAgentData?.mobile ?? /Android|iPhone|iPad|Mobile/i.test(navigator.userAgent); const touch = matchMedia('(pointer:coarse)').matches || navigator.maxTouchPoints > 0; const noHover = matchMedia('(hover:none)').matches; return debug || ua || (touch && noHover && Math.min(innerWidth,innerHeight)<900); }
function status(text, bad=false){ $('status').textContent=text; $('status').style.background=bad?'#7f1d1de8':''; }
async function initData(){ let local; try{local=await readDataset();}catch(_){} if(local){ useData(local); $('init').classList.add('hidden'); $('welcome').classList.remove('hidden'); refreshDataset(local,CONFIG).then(useData); return; } try { const value=await downloadDataset(CONFIG,p=>{if(p!==null)$('progress').value=p}); useData(value); $('init').classList.add('hidden'); $('welcome').classList.remove('hidden'); } catch(e){ $('init-status').textContent=`Data zastávek nelze připravit: ${e.message}. Zkuste to znovu online.`; $('progress').removeAttribute('value'); } }
function useData(value){ state.dataset=value; state.grid=buildGrid(value.data.stops.filter(s=>s.physical!==false),CONFIG.gridCellDegrees); $('dataset-status').textContent=datasetReadyMessage(value.meta); if(state.position) updateNearby(); }
async function start(){ $('start').disabled=true; const errors=[]; try{state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false}); $('camera').srcObject=state.stream; await $('camera').play();}catch(e){errors.push('Kamera nebyla povolena');}
 const orientation=new OrientationController(h=>{state.heading=h; scheduleProjection()}); try{await orientation.start();}catch(e){errors.push(e.message)}
 if(debug){setPosition({...CONFIG.debugPosition,timestamp:Date.now()}); window.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')state.heading=(state.heading-5+360)%360;if(e.key==='ArrowRight')state.heading=(state.heading+5)%360;scheduleProjection()});}
 else if(navigator.geolocation) state.watch=navigator.geolocation.watchPosition(p=>setPosition({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,timestamp:p.timestamp}),()=>status('Polohu nelze zjistit. Povolte přístup k poloze.',true),{enableHighAccuracy:true,maximumAge:3000,timeout:15000}); else errors.push('GPS není podporována');
 $('welcome').classList.add('hidden');$('hud').classList.remove('hidden'); if(errors.length)status(errors.join(' · '),true); else status('Hledám zastávky v okolí…'); requestAnimationFrame(loop); }
function setPosition(position){state.position=position;updateNearby();}
function updateNearby(){if(!state.grid||!state.position)return;state.nearby=nearbyFromGrid(state.grid,state.position,CONFIG.nearbyRadiusMeters,CONFIG.gridCellDegrees).slice(0,CONFIG.maxMarkers);renderMarkers();status(state.position.accuracy>CONFIG.lowAccuracyMeters?`Nepřesná poloha (±${Math.round(state.position.accuracy)} m)`:(state.nearby.length?`${state.nearby.length} zastávek v okolí`:'V okruhu 300 m nejsou zastávky'),state.position.accuracy>CONFIG.lowAccuracyMeters);}
function renderMarkers(){const root=$('markers');root.replaceChildren(...state.nearby.map(stop=>{const b=document.createElement('button');b.className='marker';b.dataset.id=stop.id;b.innerHTML=`<strong>${escapeHtml(stop.kind==='metro_entrance'?'METRO · '+stop.name:stop.name)}</strong><span>${escapeHtml(stop.platform||stop.lines?.join(' / ')||'')} · ${Math.round(stop.distance)} m</span>`;b.onclick=()=>select(stop);return b;}));scheduleProjection();}
let projectionPending=false;function scheduleProjection(){if(projectionPending)return;projectionPending=true;requestAnimationFrame(()=>{projectionPending=false;project()})}
function project(){let left=false,right=false,closest=null;for(const stop of state.nearby){const diff=angleDifference(stop.bearing,state.heading),el=document.querySelector(`.marker[data-id="${CSS.escape(stop.id)}"]`);if(!el)continue;const visible=Math.abs(diff)<=CONFIG.horizontalFovDeg/2;el.classList.toggle('hidden',!visible);if(visible){el.style.left=`${50+(diff/CONFIG.horizontalFovDeg)*100}%`;if(!closest||Math.abs(diff)<Math.abs(closest.diff))closest={stop,diff};}else if(diff<0)left=true;else right=true;} $('edge-left').classList.toggle('hidden',!left);$('edge-right').classList.toggle('hidden',!right);const target=closest&&Math.abs(closest.diff)<=CONFIG.selectionAngleDeg?closest:null;if(state.aimed?.id!==target?.stop.id){state.aimed=target?.stop||null;state.dwellAt=performance.now();}document.querySelectorAll('.marker').forEach(el=>el.classList.toggle('aimed',el.dataset.id===state.aimed?.id));debugInfo(closest?.diff);}
function loop(now){if(state.aimed&&!state.selected&&now-state.dwellAt>=CONFIG.selectionDwellMs&&now>=state.lockedUntil)select(state.aimed);requestAnimationFrame(loop)}
function select(stop){if(Date.now()<state.lockedUntil&&state.selected?.id!==stop.id)return;state.selected=stop;state.lockedUntil=Date.now()+CONFIG.selectionLockMs;$('board').classList.remove('hidden');$('board-name').textContent=stop.name;$('board-platform').textContent=stop.kind==='metro_entrance'?'stanice metra '+(stop.lines||[]).join(' / '):stop.platform?`stanoviště ${stop.platform}`:stop.kind==='train_station'?'železniční stanice':'';loadDepartures();startPolling();}
function closeBoard(){state.selected=null;$('board').classList.add('hidden');clearInterval(state.poll);state.poll=null;}
async function loadDepartures(){const selected=state.selected;if(!selected)return;state.realtime='loading';$('departures').innerHTML='<div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div>';$('board-note').textContent='Načítám aktuální odjezdy…';try{const data=await getDepartures(selected.stopId||selected.id);if(state.selected?.id!==selected.id)return;renderDepartures(data.departures);state.realtime='ok';$('board-note').textContent=`Aktualizováno ${new Date().toLocaleTimeString('cs-CZ',{hour:'2-digit',minute:'2-digit'})}`;}catch(e){state.realtime='error';$('departures').innerHTML='';$('board-note').textContent=e.message;}}
function renderDepartures(rows){$('departures').replaceChildren(...rows.slice(0,8).map(d=>{const row=document.createElement('div');row.className='departure';const minutes=Number.isFinite(d.minutes)?(d.minutes<=0?'nyní':`${d.minutes} min`):(d.scheduledTime||'—');row.innerHTML=`<span class="line">${escapeHtml(d.route||'?')}</span><span class="destination">${escapeHtml(d.destination||'Neznámý cíl')}${d.platform?`<small> · ${escapeHtml(d.platform)}</small>`:''}</span><span class="time">${escapeHtml(minutes)}</span>`;return row;}));}
function startPolling(){clearInterval(state.poll);state.poll=setInterval(()=>{if(!document.hidden)loadDepartures()},CONFIG.realtimeRefreshMs)}
function debugInfo(diff){if(!debug)return;$('debug').classList.remove('hidden');$('debug').textContent=`lat/lon: ${state.position?.latitude?.toFixed(5)||'—'}, ${state.position?.longitude?.toFixed(5)||'—'}\naccuracy: ${state.position?.accuracy||'—'} m\nheading: ${state.heading.toFixed(1)}°\nnearby: ${state.nearby.length}\nselected: ${state.selected?.id||'—'}\nbearing: ${state.aimed?.bearing?.toFixed(1)||'—'}\ndifference: ${diff?.toFixed(1)||'—'}\nrealtime: ${state.realtime}`;}
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function standalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true} window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;if(!standalone())$('install').classList.remove('hidden')});$('install').onclick=async()=>{await state.installPrompt?.prompt();$('install').classList.add('hidden')};
$('start').onclick=start;$('close-board').onclick=closeBoard;$('about-open').onclick=()=>$('about').showModal();$('about-close').onclick=()=>$('about').close();document.addEventListener('visibilitychange',()=>{if(!document.hidden&&state.selected)loadDepartures()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');if(isMobile()){$('mobile').classList.remove('hidden');initData()}else $('desktop').classList.remove('hidden');
