import { CONFIG } from './config.js'; import { buildGrid, nearbyFromGrid, angleDifference } from './geo.js'; import { readDataset, downloadDataset, refreshDataset } from './storage.js'; import { OrientationController } from './orientation.js'; import { getDepartures } from '../api/departures.js';
import { datasetReadyMessage } from './dataset-status.js';
import { CURRENT_BUILD_VERSION } from './build-version.js'; import { checkForBuildUpdate } from './build-update.js';
import { PositionStabilizer } from './position-stabilizer.js'; import { ALL_MODES, markerModes, markerAriaLabel, filterMarkers, deduplicateMetroEntrances, collisionLayout, markerPresentation } from './markers.js';
import { TRANSIT_ICONS, METRO_LINE_COLORS, METRO_LINE_ORDER, transitIconNames, departureHasNightIndicator, markerHasNightIndicator } from './transit.js';
import { setupInstallUx } from './install.js';
import { ServiceAreaTracker } from './service-area.js';
import { createEnhancedARState, detectEnhancedAR, startEnhancedAR } from './enhanced-ar.js';
import { CameraController } from './camera.js';
import { PermissionController, PermissionPanelView } from './permissions.js';
const $ = id => document.getElementById(id), debug = new URLSearchParams(location.search).get('debug') === '1';
const savedModes=JSON.parse(localStorage.getItem('pid-ar-modes')||'null');const state = { dataset:null, grid:null, position:null, rawPosition:null, serviceArea:null, serviceAreaState:'unknown', heading:null, orientation:{}, orientationStartedAt:null, orientationError:null, enhancedAR:createEnhancedARState(), nearby:[], markerLayout:[], selected:null, aimed:null, dwellAt:0, lockedUntil:0, stream:null, watch:null, poll:null, realtime:'idle', realtimeUrl:'—', realtimeStatus:'—',enabledModes:new Set(Array.isArray(savedModes)?savedModes:ALL_MODES),showNightStopsDuringDay:localStorage.getItem('pid-ar-night-stops-during-day')==='true' };
state.enhancedAR.enabled=localStorage.getItem('pid-ar-enhanced')==='true';
const camera=new CameraController($('camera'));
let permissions,locationStabilizer,orientation,enhancedARAttempt=null;
function isMobile() { const ua = navigator.userAgentData?.mobile ?? /Android|iPhone|iPad|Mobile/i.test(navigator.userAgent); const touch = matchMedia('(pointer:coarse)').matches || navigator.maxTouchPoints > 0; const noHover = matchMedia('(hover:none)').matches; return debug || ua || (touch && noHover && Math.min(innerWidth,innerHeight)<900); }
function status(text, bad=false){ $('status').textContent=text; $('status').style.background=bad?'#7f1d1de8':''; }
async function loadServiceArea(){try{const response=await fetch(CONFIG.serviceAreaUrl,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);state.serviceArea=new ServiceAreaTracker(await response.json());if(state.position)updateNearby()}catch(_){/* Geofence must never prevent use of cached stop data. */}}
async function initData(){ loadServiceArea();let local; try{local=await readDataset();}catch(_){} if(local){ useData(local); $('init').classList.add('hidden'); $('welcome').classList.remove('hidden'); refreshDataset(local,CONFIG).then(useData); return; } try { const value=await downloadDataset(CONFIG,p=>{if(p!==null)$('progress').value=p}); useData(value); $('init').classList.add('hidden'); $('welcome').classList.remove('hidden'); } catch(e){ $('init-status').textContent=`Data zastávek nelze připravit: ${e.message}. Zkuste to znovu online.`; $('progress').removeAttribute('value'); } }
function useData(value){ state.dataset=value; state.grid=buildGrid(value.data.stops.filter(s=>s.physical!==false),CONFIG.gridCellDegrees); $('dataset-status').textContent=datasetReadyMessage(value.meta); if(state.position) updateNearby(); }
function startOrientation(){orientation?.stop();orientation=new OrientationController((h,details)=>{state.orientation=details;state.orientationError=null;if(!state.enhancedAR.active)state.heading=h;scheduleProjection()},message=>status(message,true),CONFIG);orientation.start();state.orientationStartedAt=Date.now();state.orientationError=null;setTimeout(scheduleProjection,CONFIG.orientationStartupFallbackMs);return orientation;}
function startLocation(){return new Promise((resolve,reject)=>{if(!navigator.geolocation){reject(Object.assign(new Error('GPS není podporována'),{name:'NotSupportedError'}));return}navigator.geolocation.getCurrentPosition(position=>{const raw={latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy:position.coords.accuracy,speed:position.coords.speed,timestamp:position.timestamp};state.rawPosition=raw;locationStabilizer??=new PositionStabilizer(CONFIG,setPosition);locationStabilizer.add(raw);if(state.watch!==null)navigator.geolocation.clearWatch(state.watch);state.watch=navigator.geolocation.watchPosition(p=>{state.rawPosition={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,speed:p.coords.speed,timestamp:p.timestamp};locationStabilizer.add(state.rawPosition);debugInfo()},error=>{if(error.code===1)permissions?.set('location','denied');status('Polohu nelze zjistit. Povolte přístup k poloze.',true)},{enableHighAccuracy:true,maximumAge:3000,timeout:15000});resolve(position)},reject,{enableHighAccuracy:true,maximumAge:0,timeout:15000})})}
function createPermissions(){const view=new PermissionPanelView({panel:$('permission-panel'),summary:$('permission-summary'),list:$('permission-list'),button:$('permission-retry'),help:$('permission-help'),helpText:$('permission-help-text'),helpClose:$('permission-help-close')});return new PermissionController({view,startCamera:()=>enhancedARAttempt?enhancedARAttempt.then(active=>active?null:camera.start()).then(stream=>{state.stream=stream;return stream}):camera.start().then(stream=>{state.stream=stream;return stream}),startLocation,startOrientation,onChange:states=>{$('markers').classList.toggle('hidden',states.orientation!=='granted')}})}
function beginEnhancedAR(){
 state.enhancedAR.error=null;
 enhancedARAttempt=startEnhancedAR({state:state.enhancedAR,root:$('mobile'),getCompassHeading:()=>state.orientation.compassHeading,
  stopCamera:()=>{camera.stop();state.stream=null},restoreCamera:()=>{state.heading=state.orientation.fusedHeading??state.heading;$('mobile').classList.remove('xr-active');if(!camera.hasStream())restartCamera();scheduleProjection()},
  onHeading:heading=>{state.heading=heading;scheduleProjection()},onFrame:debugInfo
 }).then(active=>{if(active)$('mobile').classList.add('xr-active');else state.heading=state.orientation.fusedHeading??state.heading;return active}).finally(()=>{enhancedARAttempt=null});
 return enhancedARAttempt;
}
async function start(){ $('start').disabled=true; permissions??=createPermissions();
 const recovery=permissions.recover();
 if(state.enhancedAR.enabled&&state.enhancedAR.available)beginEnhancedAR();
 if(debug){setPosition({...CONFIG.debugPosition,timestamp:Date.now()});window.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')state.heading=(state.heading-5+360)%360;if(e.key==='ArrowRight')state.heading=(state.heading+5)%360;scheduleProjection()});}
 $('welcome').classList.add('hidden');$('hud').classList.remove('hidden');status('Kontroluji oprávnění…');await recovery;if(Object.values(permissions.states).every(value=>value==='granted'))status('Hledám zastávky v okolí…');requestAnimationFrame(loop); }
function setPosition(position){state.position=position;updateNearby();}
function updateNearby(){if(!state.grid||!state.position)return;state.nearby=deduplicateMetroEntrances(filterMarkers(nearbyFromGrid(state.grid,state.position,CONFIG.nearbyRadiusMeters,CONFIG.gridCellDegrees),state.enabledModes)).slice(0,CONFIG.maxMarkers);state.serviceAreaState=state.serviceArea?.update(state.position)||'unknown';renderMarkers();const inaccurate=state.position.accuracy>CONFIG.lowAccuracyMeters;if(state.serviceAreaState==='outside')status('Jste mimo oblast PID\nTady zatím zastávky PID nedokážu najít.',true);else status(inaccurate?`Nepřesná poloha (±${Math.round(state.position.accuracy)} m)`:(state.nearby.length?`${state.nearby.length} zastávek v okolí`:'V okruhu 300 m nejsou zastávky.'),inaccurate);}
function iconHtml(file,night=false){return `<img class="transit-icon${night?' night-icon':''}" src="icons/transit/${file}" alt="" aria-hidden="true">`}
function renderMarkers(){const root=$('markers'),now=new Date();root.replaceChildren(...state.nearby.map(stop=>{const b=document.createElement('button'),modes=markerModes(stop),showNight=markerHasNightIndicator(stop,now,CONFIG,state.showNightStopsDuringDay),icons=transitIconNames(modes,showNight);b.className='marker';b.dataset.id=stop.id;const lines=(modes.length===1&&modes[0]===1?stop.lines:[])?.filter(line=>METRO_LINE_COLORS[line]).sort((a,b)=>METRO_LINE_ORDER.indexOf(a)-METRO_LINE_ORDER.indexOf(b))||[];b.setAttribute('aria-label',markerAriaLabel({...stop,lines},showNight));if(lines.length)b.style.setProperty('--metro-strip',`linear-gradient(to right, ${lines.map((line,index)=>`${METRO_LINE_COLORS[line]} ${index/lines.length*100}% ${(index+1)/lines.length*100}%`).join(',')})`);b.classList.toggle('metro-marker',lines.length>0);const details=lines.length?`<span class="marker-details"><span class="metro-lines" aria-hidden="true">${lines.map(line=>`<span class="metro-line metro-line-${line}" style="--line-color:${METRO_LINE_COLORS[line]}">${line}</span>`).join('')}</span><span class="marker-distance">${Math.round(stop.distance)} m</span></span>`:`<span class="surface-details">${stop.platform?`<span class="platform-label">stanoviště ${escapeHtml(stop.platform)}</span><span aria-hidden="true"> · </span>`:''}${Math.round(stop.distance)} m</span>`;b.innerHTML=`<span class="marker-icons">${icons.map(file=>iconHtml(file,file==='travel-night.svg')).join('')}</span><span class="marker-copy"><strong>${escapeHtml(stop.name)}</strong>${details}</span>`;b.onclick=()=>select(stop);return b;}));scheduleProjection();}
let projectionPending=false;function scheduleProjection(){if(projectionPending)return;projectionPending=true;requestAnimationFrame(()=>{projectionPending=false;project()})}
function project(){let closest=null;const visible=[];if(state.heading===null){document.querySelectorAll('.marker').forEach(el=>el.classList.add('hidden'));state.markerLayout=[];if(state.enhancedAR.active&&!Number.isFinite(state.enhancedAR.xrHeading))status('Inicializuji vylepšené AR…');else if(state.orientationError)status('Nepodařilo se určit směr telefonu. Povolte přístup k pohybovým senzorům.',true);else if(state.orientationStartedAt&&Date.now()-state.orientationStartedAt>=CONFIG.orientationStartupFallbackMs)status('Čekám na kompas…',true);debugInfo();return}for(const stop of state.nearby){const diff=angleDifference(stop.bearing,state.heading),el=document.querySelector(`.marker[data-id="${CSS.escape(stop.id)}"]`);if(!el)continue;const shown=Math.abs(diff)<=CONFIG.horizontalFovDeg/2;el.classList.toggle('hidden',!shown);if(shown){const x=50+(diff/CONFIG.horizontalFovDeg)*100,box=el.getBoundingClientRect();visible.push({...stop,diff,x,width:box.width,height:box.height});}}const prioritized=markerPresentation(visible,CONFIG.nearStopPriorityDistanceM);state.markerLayout=collisionLayout(prioritized,{viewportWidth:innerWidth,minGap:10});for(const item of state.markerLayout){const el=document.querySelector(`.marker[data-id="${CSS.escape(item.id)}"]`);el.style.left=`calc(${item.x}% + ${item.xOffset}px)`;el.style.top=`calc(46% + ${item.offset}px)`;el.style.zIndex=String(item.zIndex);el.style.opacity=String(item.opacity);el.dataset.zone=item.zone;el.dataset.priority=String(item.priority);}const targetCandidates=prioritized.filter(item=>Math.abs(item.diff)<=CONFIG.selectionAngleDeg);if(targetCandidates.length){const item=targetCandidates.sort((a,b)=>(a.zone==='near'?0:1)-(b.zone==='near'?0:1)||Math.abs(a.diff)-Math.abs(b.diff)||a.distance-b.distance)[0];closest={stop:item,diff:item.diff};}if(state.aimed?.id!==closest?.stop.id){state.aimed=closest?.stop||null;state.dwellAt=performance.now();}document.querySelectorAll('.marker').forEach(el=>el.classList.toggle('aimed',el.dataset.id===state.aimed?.id));debugInfo(closest?.diff);}
function loop(now){if(state.aimed&&!state.selected&&now-state.dwellAt>=CONFIG.selectionDwellMs&&now>=state.lockedUntil)select(state.aimed);requestAnimationFrame(loop)}
function select(stop){if(Date.now()<state.lockedUntil&&state.selected?.id!==stop.id)return;state.selected=stop;state.lockedUntil=Date.now()+CONFIG.selectionLockMs;$('board').classList.remove('hidden');$('board-name').textContent=stop.name;$('board-platform').textContent=stop.kind==='metro_entrance'?'stanice metra '+(stop.lines||[]).join(' / '):stop.platform?`stanoviště ${stop.platform}`:stop.kind==='train_station'?'železniční stanice':'';loadDepartures();startPolling();}
function closeBoard(){state.selected=null;$('board').classList.add('hidden');clearInterval(state.poll);state.poll=null;}
async function loadDepartures(){const selected=state.selected;if(!selected)return;state.realtime='loading';state.realtimeStatus='—';$('departures').innerHTML='<div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div>';$('board-note').textContent='Načítám aktuální odjezdy…';try{const ids=selected.kind==='metro_entrance'?selected.departureStopIds:(selected.departureStopIds||selected.stopId||selected.id);const data=await getDepartures(ids,undefined,info=>{state.realtimeUrl=info.url;state.realtimeStatus=info.status??'—'});if(state.selected?.id!==selected.id)return;renderDepartures(data.departures);state.realtime='ok';$('board-note').textContent=`Aktualizováno ${new Date().toLocaleTimeString('cs-CZ',{hour:'2-digit',minute:'2-digit'})}`;}catch(e){state.realtime='error';$('departures').innerHTML='';$('board-note').textContent=debug&&typeof e.debugMessage==='function'?e.debugMessage():e.message;}finally{debugInfo();}}
const wheelchairIcon='<svg class="departure-icon" viewBox="0 0 24 24" role="img" aria-label="nízkopodlažní / bezbariérový spoj"><circle cx="10" cy="4" r="2"/><path d="M9 7v7h6l3.5 5 2-1.2-4.2-6H12v-2h4V7H9zm1 13a6 6 0 0 1-2-11.7v2.6A3.6 3.6 0 1 0 13.5 15h2.6A6 6 0 0 1 10 20z"/></svg>';
const airConditionedIcon='<svg class="departure-icon" viewBox="0 0 24 24" role="img" aria-label="klimatizovaný spoj"><path d="M11 2h2v7.2l3.1-3.1 1.4 1.4-4.1 4.1 4.1 4.1-1.4 1.4-3.1-3.1V22h-2v-7.9l-3.1 3.1-1.4-1.4 4.1-4.1-4.1-4.1 1.4-1.4L11 9.2V2zM2.5 7.9l1-1.7 6.2 3.6-.7 1.9-6.5-3.8zm12.4 4.4.7-1.9 6 3.5-1 1.7-5.7-3.3zM2.5 16.1 9 12.3l.7 1.9-6.2 3.6-1-1.7zm13.1-6.5-.7-1.9 5.7-3.3 1 1.7-6 3.5z"/></svg>';
function renderDepartures(rows){$('departures').replaceChildren(...rows.slice(0,8).map(d=>{const row=document.createElement('div');row.className='departure';const minutes=Number.isFinite(d.minutes)?(d.minutes<=0?'nyní':`${d.minutes} min`):(d.scheduledTime||'—');const night=departureHasNightIndicator(d);const icons=`${night?'<span class="night-service" aria-label="noční provoz">'+iconHtml('travel-night.svg',true)+'</span>':''}${d.wheelchairAccessible===true?wheelchairIcon:''}${d.airConditioned===true?airConditionedIcon:''}`;row.innerHTML=`<span class="line">${escapeHtml(d.route||'?')}</span><span class="destination"><span class="destination-text">${escapeHtml(d.destination||'Neznámý cíl')}</span>${icons}</span><span class="time">${escapeHtml(minutes)}</span>`;return row;}));}
function startPolling(){clearInterval(state.poll);state.poll=setInterval(()=>{if(!document.hidden)loadDepartures()},CONFIG.realtimeRefreshMs)}
function debugInfo(diff){if(!debug)return;const point=p=>p?`${p.latitude.toFixed(5)}, ${p.longitude.toFixed(5)} (±${Math.round(p.accuracy)} m)`:'—',angle=v=>Number.isFinite(v)?`${v.toFixed(1)}°`:'—',yes=value=>value?'ano':'ne',markers=state.markerLayout.map(m=>`${m.id}: ${Math.round(m.distance)} m | ${m.zone} | opacity ${m.opacity} | priority ${m.priority}`).join('\n')||'—',xrPosition=state.enhancedAR.viewerPose?.transform?.position??state.enhancedAR.viewerPose?.views?.[0]?.transform?.position;$('debug').classList.remove('hidden');$('debug').textContent=`build version: ${CURRENT_BUILD_VERSION}\ndataset version: ${state.dataset?.meta?.version||'—'}\nrealtime request URL: ${state.realtimeUrl}\nrealtime HTTP status: ${state.realtimeStatus}\nstandard fused compass heading: ${angle(state.orientation.fusedHeading)}\ncompass heading: ${angle(state.orientation.compassHeading)}\nrelative/gyro heading: ${angle(state.orientation.relativeHeading)}\ncompass correction: ${angle(state.orientation.compassCorrection)}\nGPS anchor: ${point(state.position)}\nPID service area: ${state.serviceAreaState}\nraw GPS: ${point(state.rawPosition)}\nWebXR supported: ${yes(state.enhancedAR.available)}\nWebXR session created: ${yes(state.enhancedAR.sessionCreated)}\nXRWebGLLayer created: ${yes(state.enhancedAR.layerCreated)}\nDOM Overlay active: ${yes(state.enhancedAR.domOverlayActive)}\nXR pose available: ${yes(state.enhancedAR.poseAvailable)}\ncurrent XR yaw: ${angle(state.enhancedAR.xrYaw)}\ncompass available: ${yes(Number.isFinite(state.orientation.compassHeading))}\ninitial compass heading: ${angle(state.enhancedAR.initialCompassHeading)}\nXR heading: ${angle(state.enhancedAR.xrHeading)}\nXR error: ${state.enhancedAR.error?.message||'—'}\nXR position x/y/z: ${xrPosition?`${xrPosition.x.toFixed(3)} / ${xrPosition.y.toFixed(3)} / ${xrPosition.z.toFixed(3)}`:'—'}\nnearby: ${state.nearby.length}\nselected: ${state.selected?.id||'—'}\nbearing: ${state.aimed?.bearing?.toFixed(1)||'—'}\ndifference: ${diff?.toFixed(1)||'—'}\nrealtime: ${state.realtime}\nmarkers:\n${markers}`;}
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
setupInstallUx({button:$('install'),dialog:$('install-help'),message:$('install-help-message'),closeButton:$('install-help-close')});
$('start').onclick=start;$('close-board').onclick=closeBoard;$('about-open').onclick=()=>$('about').showModal();$('about-close').onclick=()=>$('about').close();
const modeNames=new Map([[0,'Tramvaj'],[1,'Metro'],[2,'Vlak'],[3,'Autobus'],[4,'Přívoz'],[7,'Lanovka'],[11,'Trolejbus']]);
function setupFilter(){
 const modeOptions=ALL_MODES.map(mode=>{const label=document.createElement('label'),input=document.createElement('input'),icon=document.createElement('img');input.type='checkbox';input.checked=state.enabledModes.has(mode);icon.className='filter-icon';icon.src=`icons/transit/${TRANSIT_ICONS[mode]}`;icon.alt='';icon.setAttribute('aria-hidden','true');input.onchange=()=>{input.checked?state.enabledModes.add(mode):state.enabledModes.delete(mode);localStorage.setItem('pid-ar-modes',JSON.stringify([...state.enabledModes]));$('filter-open').classList.toggle('active',state.enabledModes.size!==ALL_MODES.length);updateNearby()};label.append(input,icon,modeNames.get(mode));return label});
 const nightLabel=document.createElement('label'),nightInput=document.createElement('input');nightLabel.className='filter-night-option';nightInput.type='checkbox';nightInput.checked=state.showNightStopsDuringDay;nightInput.onchange=()=>{state.showNightStopsDuringDay=nightInput.checked;localStorage.setItem('pid-ar-night-stops-during-day',String(nightInput.checked));renderMarkers()};nightLabel.append(nightInput,'Zobrazovat noční zastávky ve dne');
 const enhancedOptions=[];if(state.enhancedAR.available){const label=document.createElement('label'),input=document.createElement('input');label.className='enhanced-ar-option';input.type='checkbox';input.checked=state.enhancedAR.enabled;input.onchange=()=>setEnhancedAREnabled(input.checked);label.append(input,'Vylepšené AR (experimentální)');enhancedOptions.push(label)}
 $('filter-options').replaceChildren(...modeOptions,nightLabel,...enhancedOptions);
}
function setEnhancedAREnabled(enabled){state.enhancedAR.enabled=enabled;localStorage.setItem('pid-ar-enhanced',String(enabled));$('enhanced-ar-toggle').checked=enabled;setupFilter()}
$('enhanced-ar-toggle').onchange=event=>setEnhancedAREnabled(event.target.checked);
$('filter-open').onclick=()=>{$('filter').showModal()};$('filter-all').onclick=()=>{state.enabledModes=new Set(ALL_MODES);localStorage.setItem('pid-ar-modes',JSON.stringify(ALL_MODES));setupFilter();$('filter-open').classList.remove('active');updateNearby()};setupFilter();$('filter-open').classList.toggle('active',state.enabledModes.size!==ALL_MODES.length);
let registration; async function checkBuild(){if(registration)try{await checkForBuildUpdate({registration,currentVersion:CURRENT_BUILD_VERSION})}catch(_){/* offline */}}
function restartCamera(){camera.start().then(stream=>{state.stream=stream}).catch(()=>status('Kameru nelze znovu spustit.',true))}
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(!state.enhancedAR.active){camera.stop();state.stream=null}return}if(!state.enhancedAR.active){if(permissions)permissions.handleVisibility();else restartCamera()}if(state.selected)loadDepartures();checkBuild()});
window.addEventListener('pageshow',()=>{if(!document.hidden&&!state.enhancedAR.active&&!camera.hasStream()&&$('start').disabled)restartCamera()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(value=>{registration=value;checkBuild()});if(isMobile()){$('mobile').classList.remove('hidden');initData()}else $('desktop').classList.remove('hidden');
detectEnhancedAR().then(available=>{state.enhancedAR.available=available;$('enhanced-ar-welcome').classList.toggle('hidden',!available);$('enhanced-ar-toggle').checked=state.enhancedAR.enabled;setupFilter();debugInfo()});
