import { CONFIG } from './config.js'; import { buildGrid, nearbyFromGrid, angleDifference } from './geo.js'; import { readDataset, downloadDataset, refreshDataset } from './storage.js'; import { OrientationController } from './orientation.js'; import { getDepartures } from '../api/departures.js';
import { datasetReadyMessage } from './dataset-status.js';
import { CURRENT_BUILD_VERSION } from './build-version.js'; import { checkForBuildUpdate } from './build-update.js';
import { PositionStabilizer } from './position-stabilizer.js'; import { ALL_MODES, markerModes, filterMarkers, deduplicateMetroEntrances, collisionLayout } from './markers.js';
import { TRANSIT_ICONS, METRO_LINE_COLORS, METRO_LINE_ORDER, transitIconNames, departureHasNightIndicator } from './transit.js';
const $ = id => document.getElementById(id), debug = new URLSearchParams(location.search).get('debug') === '1';
const savedModes=JSON.parse(localStorage.getItem('pid-ar-modes')||'null');const state = { dataset:null, grid:null, position:null, heading:null, nearby:[], selected:null, aimed:null, dwellAt:0, lockedUntil:0, stream:null, watch:null, poll:null, realtime:'idle', realtimeUrl:'—', realtimeStatus:'—', installPrompt:null,enabledModes:new Set(Array.isArray(savedModes)?savedModes:ALL_MODES) };
function isMobile() { const ua = navigator.userAgentData?.mobile ?? /Android|iPhone|iPad|Mobile/i.test(navigator.userAgent); const touch = matchMedia('(pointer:coarse)').matches || navigator.maxTouchPoints > 0; const noHover = matchMedia('(hover:none)').matches; return debug || ua || (touch && noHover && Math.min(innerWidth,innerHeight)<900); }
function status(text, bad=false){ $('status').textContent=text; $('status').style.background=bad?'#7f1d1de8':''; }
async function initData(){ let local; try{local=await readDataset();}catch(_){} if(local){ useData(local); $('init').classList.add('hidden'); $('welcome').classList.remove('hidden'); refreshDataset(local,CONFIG).then(useData); return; } try { const value=await downloadDataset(CONFIG,p=>{if(p!==null)$('progress').value=p}); useData(value); $('init').classList.add('hidden'); $('welcome').classList.remove('hidden'); } catch(e){ $('init-status').textContent=`Data zastávek nelze připravit: ${e.message}. Zkuste to znovu online.`; $('progress').removeAttribute('value'); } }
function useData(value){ state.dataset=value; state.grid=buildGrid(value.data.stops.filter(s=>s.physical!==false),CONFIG.gridCellDegrees); $('dataset-status').textContent=datasetReadyMessage(value.meta); if(state.position) updateNearby(); }
async function start(){ $('start').disabled=true; const errors=[]; try{state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false}); $('camera').srcObject=state.stream; await $('camera').play();}catch(e){errors.push('Kamera nebyla povolena');}
 const orientation=new OrientationController(h=>{state.heading=h; scheduleProjection()},message=>status(message,true),CONFIG); try{await orientation.start();}catch(e){errors.push(e.message)}
 if(debug){setPosition({...CONFIG.debugPosition,timestamp:Date.now()}); window.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')state.heading=(state.heading-5+360)%360;if(e.key==='ArrowRight')state.heading=(state.heading+5)%360;scheduleProjection()});}
 else if(navigator.geolocation){const stabilizer=new PositionStabilizer(CONFIG,setPosition);state.watch=navigator.geolocation.watchPosition(p=>stabilizer.add({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,speed:p.coords.speed,timestamp:p.timestamp}),()=>status('Polohu nelze zjistit. Povolte přístup k poloze.',true),{enableHighAccuracy:true,maximumAge:3000,timeout:15000});} else errors.push('GPS není podporována');
 $('welcome').classList.add('hidden');$('hud').classList.remove('hidden'); if(errors.length)status(errors.join(' · '),true); else status('Hledám zastávky v okolí…'); requestAnimationFrame(loop); }
function setPosition(position){state.position=position;updateNearby();}
function updateNearby(){if(!state.grid||!state.position)return;state.nearby=deduplicateMetroEntrances(filterMarkers(nearbyFromGrid(state.grid,state.position,CONFIG.nearbyRadiusMeters,CONFIG.gridCellDegrees),state.enabledModes)).slice(0,CONFIG.maxMarkers);renderMarkers();status(state.position.accuracy>CONFIG.lowAccuracyMeters?`Nepřesná poloha (±${Math.round(state.position.accuracy)} m)`:(state.nearby.length?`${state.nearby.length} zastávek v okolí`:'V okruhu 300 m nejsou zastávky'),state.position.accuracy>CONFIG.lowAccuracyMeters);}
function iconHtml(file,night=false){return `<img class="transit-icon${night?' night-icon':''}" src="icons/transit/${file}" alt="" aria-hidden="true">`}
function markerLabel(stop){const modes=markerModes(stop),type=modes.length===1?modeAccessibleNames.get(modes[0]):'Zastávka';return `${type}${stop.hasNightService?', noční provoz':''}, ${stop.name}, ${Math.round(stop.distance)} metrů`}
function renderMarkers(){const root=$('markers');root.replaceChildren(...state.nearby.map(stop=>{const b=document.createElement('button'),modes=markerModes(stop),icons=transitIconNames(modes,stop.hasNightService);b.className='marker';b.dataset.id=stop.id;b.setAttribute('aria-label',markerLabel(stop));const lines=stop.lines?.filter(line=>METRO_LINE_COLORS[line]).sort((a,b)=>METRO_LINE_ORDER.indexOf(a)-METRO_LINE_ORDER.indexOf(b))||[];if(lines.length)b.style.setProperty('--metro-strip',`linear-gradient(to right, ${lines.map((line,index)=>`${METRO_LINE_COLORS[line]} ${index/lines.length*100}% ${(index+1)/lines.length*100}%`).join(',')})`);b.classList.toggle('metro-marker',lines.length>0);b.innerHTML=`<span class="marker-icons">${icons.map(file=>iconHtml(file,file==='travel-night.svg')).join('')}</span><span class="marker-copy"><strong>${escapeHtml(stop.name)}</strong><span>${escapeHtml(stop.platform||lines.join(' / ')||'')} ${stop.platform||lines.length?'· ':''}${Math.round(stop.distance)} m</span></span>`;b.onclick=()=>select(stop);return b;}));scheduleProjection();}
let projectionPending=false;function scheduleProjection(){if(projectionPending)return;projectionPending=true;requestAnimationFrame(()=>{projectionPending=false;project()})}
function project(){let closest=null;const visible=[];if(state.heading===null){document.querySelectorAll('.marker').forEach(el=>el.classList.add('hidden'));debugInfo();return}for(const stop of state.nearby){const diff=angleDifference(stop.bearing,state.heading),el=document.querySelector(`.marker[data-id="${CSS.escape(stop.id)}"]`);if(!el)continue;const shown=Math.abs(diff)<=CONFIG.horizontalFovDeg/2;el.classList.toggle('hidden',!shown);if(shown){const x=50+(diff/CONFIG.horizontalFovDeg)*100;visible.push({...stop,diff,x});if(!closest||Math.abs(diff)<Math.abs(closest.diff)||Math.abs(diff)===Math.abs(closest.diff)&&stop.distance<closest.stop.distance)closest={stop,diff};}}for(const item of collisionLayout(visible)){const el=document.querySelector(`.marker[data-id="${CSS.escape(item.id)}"]`);el.style.left=`${item.x}%`;el.style.top=`calc(46% + ${item.offset}px)`;el.style.zIndex=String(1000-Math.round(item.distance));}const target=closest&&Math.abs(closest.diff)<=CONFIG.selectionAngleDeg?closest:null;if(state.aimed?.id!==target?.stop.id){state.aimed=target?.stop||null;state.dwellAt=performance.now();}document.querySelectorAll('.marker').forEach(el=>el.classList.toggle('aimed',el.dataset.id===state.aimed?.id));debugInfo(closest?.diff);}
function loop(now){if(state.aimed&&!state.selected&&now-state.dwellAt>=CONFIG.selectionDwellMs&&now>=state.lockedUntil)select(state.aimed);requestAnimationFrame(loop)}
function select(stop){if(Date.now()<state.lockedUntil&&state.selected?.id!==stop.id)return;state.selected=stop;state.lockedUntil=Date.now()+CONFIG.selectionLockMs;$('board').classList.remove('hidden');$('board-name').textContent=stop.name;$('board-platform').textContent=stop.kind==='metro_entrance'?'stanice metra '+(stop.lines||[]).join(' / '):stop.platform?`stanoviště ${stop.platform}`:stop.kind==='train_station'?'železniční stanice':'';loadDepartures();startPolling();}
function closeBoard(){state.selected=null;$('board').classList.add('hidden');clearInterval(state.poll);state.poll=null;}
async function loadDepartures(){const selected=state.selected;if(!selected)return;state.realtime='loading';state.realtimeStatus='—';$('departures').innerHTML='<div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div>';$('board-note').textContent='Načítám aktuální odjezdy…';try{const ids=selected.kind==='metro_entrance'?selected.departureStopIds:(selected.departureStopIds||selected.stopId||selected.id);const data=await getDepartures(ids,undefined,info=>{state.realtimeUrl=info.url;state.realtimeStatus=info.status??'—'});if(state.selected?.id!==selected.id)return;renderDepartures(data.departures);state.realtime='ok';$('board-note').textContent=`Aktualizováno ${new Date().toLocaleTimeString('cs-CZ',{hour:'2-digit',minute:'2-digit'})}`;}catch(e){state.realtime='error';$('departures').innerHTML='';$('board-note').textContent=debug&&typeof e.debugMessage==='function'?e.debugMessage():e.message;}finally{debugInfo();}}
const wheelchairIcon='<svg class="departure-icon" viewBox="0 0 24 24" role="img" aria-label="nízkopodlažní / bezbariérový spoj"><circle cx="10" cy="4" r="2"/><path d="M9 7v7h6l3.5 5 2-1.2-4.2-6H12v-2h4V7H9zm1 13a6 6 0 0 1-2-11.7v2.6A3.6 3.6 0 1 0 13.5 15h2.6A6 6 0 0 1 10 20z"/></svg>';
const airConditionedIcon='<svg class="departure-icon" viewBox="0 0 24 24" role="img" aria-label="klimatizovaný spoj"><path d="M11 2h2v7.2l3.1-3.1 1.4 1.4-4.1 4.1 4.1 4.1-1.4 1.4-3.1-3.1V22h-2v-7.9l-3.1 3.1-1.4-1.4 4.1-4.1-4.1-4.1 1.4-1.4L11 9.2V2zM2.5 7.9l1-1.7 6.2 3.6-.7 1.9-6.5-3.8zm12.4 4.4.7-1.9 6 3.5-1 1.7-5.7-3.3zM2.5 16.1 9 12.3l.7 1.9-6.2 3.6-1-1.7zm13.1-6.5-.7-1.9 5.7-3.3 1 1.7-6 3.5z"/></svg>';
function renderDepartures(rows){$('departures').replaceChildren(...rows.slice(0,8).map(d=>{const row=document.createElement('div');row.className='departure';const minutes=Number.isFinite(d.minutes)?(d.minutes<=0?'nyní':`${d.minutes} min`):(d.scheduledTime||'—');const night=departureHasNightIndicator(d);const icons=`${night?'<span class="night-service" aria-label="noční spoj">'+iconHtml('travel-night.svg',true)+'</span>':''}${d.wheelchairAccessible===true?wheelchairIcon:''}${d.airConditioned===true?airConditionedIcon:''}`;row.innerHTML=`<span class="line">${escapeHtml(d.route||'?')}</span><span class="destination"><span class="destination-text">${escapeHtml(d.destination||'Neznámý cíl')}</span>${icons}</span><span class="time">${escapeHtml(minutes)}</span>`;return row;}));}
function startPolling(){clearInterval(state.poll);state.poll=setInterval(()=>{if(!document.hidden)loadDepartures()},CONFIG.realtimeRefreshMs)}
function debugInfo(diff){if(!debug)return;$('debug').classList.remove('hidden');$('debug').textContent=`build version: ${CURRENT_BUILD_VERSION}\ndataset version: ${state.dataset?.meta?.version||'—'}\nrealtime request URL: ${state.realtimeUrl}\nrealtime HTTP status: ${state.realtimeStatus}\nlat/lon: ${state.position?.latitude?.toFixed(5)||'—'}, ${state.position?.longitude?.toFixed(5)||'—'}\naccuracy: ${state.position?.accuracy||'—'} m\nheading: ${state.heading?.toFixed(1)||'—'}°\nnearby: ${state.nearby.length}\nselected: ${state.selected?.id||'—'}\nbearing: ${state.aimed?.bearing?.toFixed(1)||'—'}\ndifference: ${diff?.toFixed(1)||'—'}\nrealtime: ${state.realtime}`;}
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function standalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true} window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;if(!standalone())$('install').classList.remove('hidden')});$('install').onclick=async()=>{await state.installPrompt?.prompt();$('install').classList.add('hidden')};
$('start').onclick=start;$('close-board').onclick=closeBoard;$('about-open').onclick=()=>$('about').showModal();$('about-close').onclick=()=>$('about').close();
const modeNames=new Map([[0,'Tramvaj'],[1,'Metro'],[2,'Vlak'],[3,'Autobus'],[4,'Přívoz'],[7,'Lanovka'],[11,'Trolejbus']]),modeAccessibleNames=new Map([[0,'Tramvajová zastávka'],[1,'Stanice metra'],[2,'Železniční stanice'],[3,'Autobusová zastávka'],[4,'Přístaviště přívozu'],[7,'Stanice lanovky'],[11,'Trolejbusová zastávka']]);function setupFilter(){$('filter-options').replaceChildren(...ALL_MODES.map(mode=>{const label=document.createElement('label'),input=document.createElement('input'),icon=document.createElement('img');input.type='checkbox';input.checked=state.enabledModes.has(mode);icon.className='filter-icon';icon.src=`icons/transit/${TRANSIT_ICONS[mode]}`;icon.alt='';icon.setAttribute('aria-hidden','true');input.onchange=()=>{input.checked?state.enabledModes.add(mode):state.enabledModes.delete(mode);localStorage.setItem('pid-ar-modes',JSON.stringify([...state.enabledModes]));$('filter-open').classList.toggle('active',state.enabledModes.size!==ALL_MODES.length);updateNearby()};label.append(input,icon,modeNames.get(mode));return label}));}$('filter-open').onclick=()=>{$('filter').showModal()};$('filter-all').onclick=()=>{state.enabledModes=new Set(ALL_MODES);localStorage.setItem('pid-ar-modes',JSON.stringify(ALL_MODES));setupFilter();$('filter-open').classList.remove('active');updateNearby()};setupFilter();$('filter-open').classList.toggle('active',state.enabledModes.size!==ALL_MODES.length);
let registration; async function checkBuild(){if(registration)try{await checkForBuildUpdate({registration,currentVersion:CURRENT_BUILD_VERSION})}catch(_){/* offline */}}
document.addEventListener('visibilitychange',()=>{if(!document.hidden){if(state.selected)loadDepartures();checkBuild()}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(value=>{registration=value;checkBuild()});if(isMobile()){$('mobile').classList.remove('hidden');initData()}else $('desktop').classList.remove('hidden');
