import test from 'node:test';import assert from 'node:assert/strict';
import { buildMarkers } from '../scripts/pid-data-lib.mjs';import { mergeDepartures } from '../worker/src/index.js';import { OrientationController } from '../js/orientation.js';import { PositionStabilizer } from '../js/position-stabilizer.js';import { filterMarkers,deduplicateMetroEntrances,collisionLayout } from '../js/markers.js';
test('metro station maps entrance to directional stops and line',()=>{const stops=[{stop_id:'S',stop_name:'Anděl',location_type:'1',stop_lat:'50',stop_lon:'14'},{stop_id:'Z1',parent_station:'S',location_type:'0',stop_lat:'50',stop_lon:'14'},{stop_id:'Z2',parent_station:'S',location_type:'0',stop_lat:'50',stop_lon:'14'},{stop_id:'SE1',stop_name:'Anděl',parent_station:'S',location_type:'2',stop_lat:'50.1',stop_lon:'14.1'}],routes=[{route_id:'B',route_type:'1',route_short_name:'B'}],trips=[{trip_id:'t',route_id:'B'}],stopTimes=[{trip_id:'t',stop_id:'Z1'},{trip_id:'t',stop_id:'Z2'}];const [marker]=buildMarkers({stops,routes,trips,stopTimes});assert.equal(marker.name,'Anděl');assert.equal(marker.entranceId,'SE1');assert.deepEqual(marker.departureStopIds,['Z1','Z2']);assert.deepEqual(marker.lines,['B'])});
test('metro departures merge chronologically and deduplicate',()=>{const a={route:'B',destination:'Zličín',scheduledTime:'2026-01-01T10:02:00Z',platform:'1'},b={route:'A',destination:'Depo',scheduledTime:'2026-01-01T10:01:00Z'};assert.deepEqual(mergeDepartures([[a],[b,a]]),[b,a])});
test('collision and mode filter preserve nearest priority',()=>{const markers=[{id:'far',distance:20,x:50,modes:[3]},{id:'near',distance:5,x:51,modes:[0]}];assert.deepEqual(filterMarkers(markers,new Set([0])).map(x=>x.id),['near']);const laid=collisionLayout(markers);assert.equal(laid[0].id,'near');assert.equal(laid[0].offset,0);assert.notEqual(laid[1].offset,0)});

test('heading smoothing crosses north by shortest arc',()=>{let now=0;const values=[],controller=new OrientationController(h=>values.push(h),()=>{},{headingStabilizationMs:0,headingPublishIntervalMs:0,headingBufferSize:2,headingDeadbandDeg:0,headingSmallAlpha:.5,headingMediumAlpha:.5,headingTurnAlpha:.5},()=>now++);controller.handle({type:'deviceorientationabsolute',absolute:true,alpha:1});controller.handle({type:'deviceorientationabsolute',absolute:true,alpha:359});assert.ok(values[1]<1||values[1]>359)});
test('GPS stabilizer rejects one jump and confirms movement with three fixes',()=>{let now=0;const values=[],config={gpsSampleCount:5,gpsSampleMaxAccuracy:60,gpsAnchorAccuracyMeters:30,gpsStartupTimeoutMs:1000,gpsDeadbandMeters:4,gpsMoveThresholdMeters:9,gpsAccuracyImprovementRatio:.5,gpsInterpolationAlpha:.5,gpsAnchorMinIntervalMs:2500,gpsMoveConfirmationCount:3,gpsStaticSpeedMps:.5,gpsMoveConsistencyMeters:12},s=new PositionStabilizer(config,p=>values.push(p),()=>now);s.add({latitude:50,longitude:14,accuracy:20,speed:0});assert.equal(values.length,1);now=3000;s.add({latitude:50.001,longitude:14,accuracy:20,speed:1});assert.equal(values.length,1);s.add({latitude:50.0001,longitude:14,accuracy:20,speed:0});assert.equal(values.length,1);for(const latitude of [50.001,50.00101,50.00102])s.add({latitude,longitude:14,accuracy:20,speed:1});assert.equal(values.length,2);assert.ok(values[1].latitude>50&&values[1].latitude<50.00102)});
test('metro entrances are deduplicated by station and nearest wins',()=>{const markers=[{id:'far',kind:'metro_entrance',stationId:'M',distance:20},{id:'near',kind:'metro_entrance',stationId:'M',distance:10},{id:'other',kind:'metro_entrance',stationId:'N',distance:30},{id:'bus',kind:'stop',distance:5}];assert.deepEqual(deduplicateMetroEntrances(markers).map(x=>x.id),['near','other','bus'])});
