import test from 'node:test';import assert from 'node:assert/strict';
import { buildMarkers, buildMarkersWithStats } from '../scripts/pid-data-lib.mjs';import { mergeDepartures } from '../worker/src/index.js';import { OrientationController } from '../js/orientation.js';import { PositionStabilizer } from '../js/position-stabilizer.js';import { filterMarkers,deduplicateMetroEntrances,collisionLayout } from '../js/markers.js';import { TRANSIT_ICONS, isNightRoute, transitIconNames, departureHasNightIndicator, markerHasNightIndicator } from '../js/transit.js';import { CONFIG } from '../js/config.js';
test('metro station maps entrance to directional stops and line',()=>{const stops=[{stop_id:'S',stop_name:'Anděl',location_type:'1',stop_lat:'50',stop_lon:'14'},{stop_id:'Z1',parent_station:'S',location_type:'0',stop_lat:'50',stop_lon:'14'},{stop_id:'Z2',parent_station:'S',location_type:'0',stop_lat:'50',stop_lon:'14'},{stop_id:'SE1',stop_name:'Anděl',parent_station:'S',location_type:'2',stop_lat:'50.1',stop_lon:'14.1'}],routes=[{route_id:'B',route_type:'1',route_short_name:'B'}],trips=[{trip_id:'t',route_id:'B'}],stopTimes=[{trip_id:'t',stop_id:'Z1'},{trip_id:'t',stop_id:'Z2'}];const [marker]=buildMarkers({stops,routes,trips,stopTimes});assert.equal(marker.name,'Anděl');assert.equal(marker.entranceId,'SE1');assert.deepEqual(marker.departureStopIds,['Z1','Z2']);assert.deepEqual(marker.lines,['B'])});
test('technical railway stop with no passenger service is excluded',()=>{const stops=[{stop_id:'T57073',stop_name:'Pha hl.n. Lc105-102',location_type:'0',stop_lat:'50',stop_lon:'14'}],routes=[{route_id:'R',route_type:'2'}],trips=[{trip_id:'t',route_id:'R'}],stopTimes=[{trip_id:'t',stop_id:'T57073',pickup_type:'1',drop_off_type:'1'}];const result=buildMarkersWithStats({stops,routes,trips,stopTimes});assert.deepEqual(result.markers,[]);assert.deepEqual(result.statistics,{railwayPassengerStops:0,railwayTechnicalStopsExcluded:1,nightRoutesByMode:{}})});
test('railway stop with regular passenger service is preserved',()=>{const stops=[{stop_id:'P',stop_name:'Praha hlavní nádraží',location_type:'0',stop_lat:'50',stop_lon:'14'}],routes=[{route_id:'R',route_type:'2'}],trips=[{trip_id:'t',route_id:'R'}],stopTimes=[{trip_id:'t',stop_id:'P',pickup_type:'',drop_off_type:''}];const result=buildMarkersWithStats({stops,routes,trips,stopTimes});assert.equal(result.markers.length,1);assert.equal(result.markers[0].kind,'train_station');assert.deepEqual(result.statistics,{railwayPassengerStops:1,railwayTechnicalStopsExcluded:0,nightRoutesByMode:{}})});
test('metro departures merge chronologically and deduplicate',()=>{const a={route:'B',destination:'Zličín',scheduledTime:'2026-01-01T10:02:00Z',platform:'1'},b={route:'A',destination:'Depo',scheduledTime:'2026-01-01T10:01:00Z'};assert.deepEqual(mergeDepartures([[a],[b,a]]),[b,a])});
test('collision and mode filter preserve nearest priority',()=>{const markers=[{id:'far',distance:20,x:50,modes:[3]},{id:'near',distance:5,x:51,modes:[0]}];assert.deepEqual(filterMarkers(markers,new Set([0])).map(x=>x.id),['near']);const laid=collisionLayout(markers);assert.equal(laid[0].id,'near');assert.equal(laid[0].offset,0);assert.notEqual(laid[1].offset,0)});

test('heading smoothing crosses north by shortest arc',()=>{let now=0;const values=[],controller=new OrientationController(h=>values.push(h),()=>{},{headingStabilizationMs:0,headingPublishIntervalMs:0,headingBufferSize:3,headingDeadbandDeg:0,headingSmallAlpha:.5,headingMediumAlpha:.5,headingTurnAlpha:.5},()=>now++);controller.handle({type:'deviceorientationabsolute',absolute:true,alpha:1});controller.handle({type:'deviceorientationabsolute',absolute:true,alpha:359});controller.handle({type:'deviceorientationabsolute',absolute:true,alpha:0});assert.ok(values[0]<1||values[0]>359)});
test('GPS stabilizer rejects one jump and confirms movement with three fixes',()=>{let now=0;const values=[],config={gpsSampleCount:5,gpsSampleMaxAccuracy:60,gpsAnchorAccuracyMeters:30,gpsAnchorSampleCount:3,gpsAnchorSpreadMeters:10,gpsStartupTimeoutMs:1000,gpsDeadbandMeters:4,gpsMoveThresholdMeters:9,gpsAccuracyImprovementRatio:.5,gpsInterpolationAlpha:.5,gpsAnchorMinIntervalMs:2500,gpsMoveConfirmationCount:3,gpsStaticSpeedMps:.5,gpsMoveConsistencyMeters:12},s=new PositionStabilizer(config,p=>values.push(p),()=>now);for(const latitude of [50,50.00001,50.00002])s.add({latitude,longitude:14,accuracy:20,speed:0});assert.equal(values.length,1);now=3000;s.add({latitude:50.001,longitude:14,accuracy:20,speed:1});assert.equal(values.length,1);s.add({latitude:50.0001,longitude:14,accuracy:20,speed:0});assert.equal(values.length,1);for(const latitude of [50.001,50.00101,50.00102])s.add({latitude,longitude:14,accuracy:20,speed:1});assert.equal(values.length,2);assert.ok(values[1].latitude>50&&values[1].latitude<50.00102)});
test('orientation uses relative turn immediately and compass correction gradually',()=>{let now=0,last;const controller=new OrientationController((_,state)=>{last=state},()=>{},{headingStabilizationMs:0,headingPublishIntervalMs:0,headingDeadbandDeg:2.5,compassCorrectionAlpha:.1,compassCorrectionMaxDegPerSecond:2},()=>now);for(let i=0;i<3;i++)controller.handle({type:'deviceorientationabsolute',absolute:true,alpha:0});now=100;controller.handle({type:'deviceorientation',absolute:false,alpha:350});assert.ok(last.relativeHeading>9&&last.relativeHeading<11);assert.ok(last.fusedHeading>9&&last.fusedHeading<11);now=200;controller.handle({type:'deviceorientationabsolute',absolute:true,alpha:0});assert.ok(last.compassCorrection<0);assert.ok(Math.abs(last.compassCorrection)<=.21);assert.ok(last.fusedHeading>9)});
test('metro entrances are deduplicated by station and nearest wins',()=>{const markers=[{id:'far',kind:'metro_entrance',stationId:'M',distance:20},{id:'near',kind:'metro_entrance',stationId:'M',distance:10},{id:'other',kind:'metro_entrance',stationId:'N',distance:30},{id:'bus',kind:'stop',distance:5}];assert.deepEqual(deduplicateMetroEntrances(markers).map(x=>x.id),['near','other','bus'])});

test('route types map to the supplied transit icons',()=>{assert.deepEqual(TRANSIT_ICONS,{0:'travel-tram.svg',1:'travel-metro.svg',2:'travel-train.svg',3:'travel-bus.svg',4:'travel-ferry.svg',7:'travel-cableway.svg',11:'travel-trolley.svg'})});
test('night tram, bus and trolley retain their base icon',()=>{assert.deepEqual(transitIconNames([0],true),['travel-tram.svg','travel-night.svg']);assert.deepEqual(transitIconNames([3],true),['travel-bus.svg','travel-night.svg']);assert.deepEqual(transitIconNames([11],true),['travel-trolley.svg','travel-night.svg'])});
test('metro and train never receive a night icon',()=>{assert.deepEqual(transitIconNames([1],true),['travel-metro.svg']);assert.deepEqual(transitIconNames([2],true),['travel-train.svg']);assert.equal(isNightRoute({route_type:'1',route_short_name:'91'}),false);assert.equal(isNightRoute({route_type:'2',route_short_name:'901'}),false)});
test('mixed day and night lines set marker night metadata',()=>{const stops=[{stop_id:'P',stop_name:'Test',location_type:'0',stop_lat:'50',stop_lon:'14'}],routes=[{route_id:'day',route_type:'3',route_short_name:'135'},{route_id:'night',route_type:'3',route_short_name:'901'}],trips=[{trip_id:'td',route_id:'day'},{trip_id:'tn',route_id:'night'}],stopTimes=[{trip_id:'td',stop_id:'P'},{trip_id:'tn',stop_id:'P'}];const marker=buildMarkers({stops,routes,trips,stopTimes})[0];assert.equal(marker.hasNightService,true);assert.equal(marker.hasDayService,true);assert.equal(marker.nightOnly,false);assert.deepEqual(marker.dayLines,['135']);assert.deepEqual(marker.nightLines,['901'])});
test('only exact official route numbers become night departures',()=>{assert.equal(departureHasNightIndicator({route:'93',routeType:0}),true);assert.equal(departureHasNightIndicator({route:'901',routeType:3}),true);assert.equal(departureHasNightIndicator({route:'901X',routeType:3}),false);assert.equal(departureHasNightIndicator({route:'93',routeType:2}),false)});
test('mixed day/night stop has no night icon at 14:00 Prague time',()=>{const marker={modes:[3],hasNightService:true,hasDayService:true,nightLines:['901'],dayLines:['135']};assert.equal(markerHasNightIndicator(marker,new Date('2026-01-15T14:00:00+01:00'),CONFIG),false);assert.deepEqual(transitIconNames(marker.modes,false),['travel-bus.svg'])});
test('mixed day/night stop has a night icon at 00:30 Prague time',()=>{const marker={modes:[3],hasNightService:true,hasDayService:true,nightLines:['901'],dayLines:['135']};assert.equal(markerHasNightIndicator(marker,new Date('2026-01-15T00:30:00+01:00'),CONFIG),true);assert.deepEqual(transitIconNames(marker.modes,true),['travel-bus.svg','travel-night.svg'])});
test('night-only stop has a night icon at 14:00 Prague time',()=>{const marker={modes:[0],hasNightService:true,hasDayService:false,nightOnly:true,nightLines:['93'],dayLines:[]};assert.equal(markerHasNightIndicator(marker,new Date('2026-01-15T14:00:00+01:00'),CONFIG),true)});
test('a concrete night departure always has a night icon',()=>{assert.equal(departureHasNightIndicator({route:'901',routeType:3}),true);assert.deepEqual(transitIconNames([3],departureHasNightIndicator({route:'901',routeType:3})),['travel-bus.svg','travel-night.svg'])});
test('metro, train, ferry and cableway never receive a night icon',()=>{for(const mode of [1,2,4,7]){assert.equal(departureHasNightIndicator({route:'901',routeType:mode,isNight:true}),false);assert.equal(transitIconNames([mode],true).includes('travel-night.svg'),false)}});
