const GOLEMIO_URL = 'https://api.golemio.cz/v2/pid/departureboards';
const inFlight = new Map();
const json = (value, status, headers={}) => new Response(JSON.stringify(value), { status, headers:{'content-type':'application/json; charset=utf-8',...headers} });
function cors(request, env) { const origin=request.headers.get('Origin'); const allowed=(env.ALLOWED_ORIGIN||'').split(',').map(x=>x.trim()).filter(Boolean); if(!origin)return {};if(allowed.includes(origin)||allowed.includes('*'))return {'Access-Control-Allow-Origin':origin,'Vary':'Origin'};return null; }
function normalize(payload) {
  const rows = payload.departures || payload.data?.departures || [];
  return rows.map(item=>{const departure=item.departure||item;const predicted=departure.timestamp_predicted||departure.predicted||item.predicted_departure;const scheduled=departure.timestamp_scheduled||departure.scheduled||item.scheduled_departure;const when=predicted||scheduled;return {route:String(item.route?.short_name||item.route?.shortName||item.route_name||item.line||''),destination:item.trip?.headsign||item.destination?.name||item.destination||'',minutes:when?Math.max(0,Math.round((new Date(when).getTime()-Date.now())/60000)):null,scheduledTime:scheduled?new Date(scheduled).toISOString():null,realtime:Boolean(predicted),delaySeconds:item.delay?.seconds??item.delay??null,platform:item.stop?.platform_code||item.platform_code||item.platform||null};}).filter(x=>x.route||x.destination);
}
async function upstream(stop, env) {
  if (!env.GOLEMIO_API_KEY) return json({error:'Worker nemá nastavený GOLEMIO_API_KEY.'},503);
  const url=new URL(GOLEMIO_URL);url.searchParams.set('ids',stop);url.searchParams.set('limit','20');url.searchParams.set('minutesBefore','0');url.searchParams.set('minutesAfter','180');url.searchParams.set('includeMetroTrains','true');
  const response=await fetch(url,{headers:{'X-Access-Token':env.GOLEMIO_API_KEY,'Accept':'application/json'}});if(!response.ok)return json({error:'Golemio request failed',upstreamStatus:response.status},502);
  const payload=await response.json();return json({stop,departures:normalize(payload),updatedAt:new Date().toISOString()},200);
}
export default {async fetch(request,env,ctx){const headers=cors(request,env);if(headers===null)return json({error:'Origin is not allowed'},403);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{...headers,'Access-Control-Allow-Methods':'GET, OPTIONS','Access-Control-Allow-Headers':'Content-Type','Access-Control-Max-Age':'86400'}});if(request.method!=='GET')return json({error:'Method not allowed'},405,headers);
 const url=new URL(request.url);if(url.pathname==='/health'&&url.search==='')return json({ok:true},200,headers);if(url.pathname!=='/departures')return json({error:'Not found'},404,headers);const known=new Set(['stop']);for(const key of url.searchParams.keys())if(!known.has(key))return json({error:`Unknown parameter: ${key}`},400,headers);const stop=url.searchParams.get('stop');if(!stop||stop.length>64||!/^[A-Za-z0-9_.:-]+$/.test(stop))return json({error:'Invalid stop'},400,headers);
 const ttl=Math.max(5,Math.min(300,Number(env.CACHE_TTL_SECONDS)||20));const cacheKey=new Request(`${url.origin}/departures?stop=${encodeURIComponent(stop)}`,{method:'GET'});const cached=await caches.default.match(cacheKey);if(cached){const out=new Response(cached.body,cached);Object.entries(headers).forEach(([k,v])=>out.headers.set(k,v));out.headers.set('X-PID-AR-Cache','HIT');return out;}
 let promise=inFlight.get(stop);if(!promise){promise=upstream(stop,env).finally(()=>inFlight.delete(stop));inFlight.set(stop,promise)}const result=await promise;const out=new Response(result.body,result);Object.entries(headers).forEach(([k,v])=>out.headers.set(k,v));out.headers.set('Cache-Control',`public, max-age=${ttl}`);out.headers.set('X-PID-AR-Cache','MISS');if(result.ok)ctx.waitUntil(caches.default.put(cacheKey,out.clone()));return out;}};
